<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>AD-Security-Audit</AssemblyName>
    <RootNamespace>ADSecurityAuditCLI</RootNamespace>
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <DebugType>none</DebugType>
    <DebugSymbols>false</DebugSymbols>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="..\Invoke-ADSecurityAudit.ps1" Link="Resources\Invoke-ADSecurityAudit.ps1" />
    <EmbeddedResource Include="..\Config\**\*.*" Link="Resources\Config\%(RecursiveDir)%(Filename)%(Extension)" />
    <EmbeddedResource Include="..\Modules\**\*.*" Link="Resources\Modules\%(RecursiveDir)%(Filename)%(Extension)" />
  </ItemGroup>

</Project>
